config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root  action: :welcome, controller: 'site'
  post 'show_next_options/:entity/(:entity_id)', action: 'show_next_options', controller: 'site'
  post 'start_testing', action: 'start_testing', controller: 'site'
  post 'show_start_button', action: 'show_start_button', controller: 'site'
  post 'show_lecturers_list', action: 'show_lecturers_list', controller: 'site'
  post 'show_stats', action: 'show_stats', controller: 'site'
  get 'main_panel', action: 'main_panel', controller: 'site'

  resources :faculties
  resources :questionnaires
  resources :disciplines
  resources :departments
  resources :university_groups
  resources :lecturers

  scope module: 'api' do
    namespace 'v1' do
      resources :lecturers, only: [:show, :index]
      resources :disciplines, only: [:show, :index]
      resources :faculties, only: [:show, :index]
      resources :departments, only: [:show, :index]
      resources :university_groups, only: [:show, :index]
      resources :questionnaires, only: [:create]
    end
  end
  mount ActionCable.server => '/cable'
end

app/models/university_group.rb
class UniversityGroup < ApplicationRecord
  belongs_to :department
  belongs_to :faculty
  has_and_belongs_to_many :lecturers
  validates :title,
            format: { with: /\A[А-я0-9\-]+\z/, message: 'Используйте кириллические символы/цифры/дефис' },
            uniqueness: { message: 'Группа с таким названием уже существует в базе данных'},
            length: { maximum: 12, too_long: "Длина введенного названия больше максимальной — %{count}" }
  validates :faculty_id, presence: { message: 'Не указан факультет' }
  validates :department_id, presence: { message: 'Не указана кафедра' }
end

app/controllers/api/v1/university_groups_controller.rb
class Api::V1::UniversityGroupsController < Api::V1::ApiController
  before_action :set_university_group, only: [:show]
  def index
    render json: ::V1::UniversityGroupSerializer.new(UniversityGroup.all).serialized_json
  end

  def show
    render json: ::V1::UniversityGroupSerializer.new(@university_group).serialized_json
  end

  private
  def set_university_group
    @university_group = UniversityGroup.find_by(id: params[:id])
  end
end

app/controllers/university_groups_controller.rb
class UniversityGroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_university_group, only: [:show, :edit, :update, :destroy]
  def index
    @university_groups = UniversityGroup.all
  end

  def new
    @university_group = UniversityGroup.new
  end

  def edit
    @lecturers = Lecturer.all.order('fullname ASC')
  end

  def create
    @university_group = UniversityGroup.new(university_group_params)
    if @university_group.save
      flash[:success] = 'Учебная группа создана'
      redirect_to @university_group
    else
      flash[:danger] = @university_group.errors.full_messages.to_sentence
      render action: :new
    end
  end

  def show
  end

  def update
    p university_group_params[:lecturer_ids]
    if @university_group.update(university_group_params)
      flash[:success] = 'Данные учебной группы обновлены'
      redirect_to @university_group
    else
      flash[:danger] = @university_group.errors.full_messages.to_sentence
      redirect_to university_groups_path
    end
  end

  def destroy
    if @university_group.destroy
      flash[:success] = 'Учебная группа удалена'
    else
      flash[:danger] = 'Произошла ошибка'
    end
    redirect_to university_groups_path
  end

  private
    def insert_faculty(university_group)
      university_group.faculty = @university_group.department.faculty
    end

    def set_university_group
      @university_group = UniversityGroup.find_by(id: params[:id])
    end

    def university_group_params
      params.require(:university_group).permit(:title, :faculty_id, :department_id, lecturer_ids: [])
    end
end

app/helpers/university_groups_helper.rb
module UniversityGroupsHelper
end

app/views/university_groups/_form.html.haml
= form_for(university_group) do |f|
  .form-group
    = f.text_field(:title, class: 'form-control', placeholder: 'Название')
  .form-group#facultiesOptions
    = f.collection_select(:faculty_id, Faculty.all, :id, :title, { prompt: 'Выберите факультет' },
                                                                     class: 'form-control',
                                                                     onchange: "showNextOptions('faculty', this);")
  .form-group#departmentsOptions
    = f.collection_select(:department_id, Department.all, :id, :title, { prompt: 'Выберите кафедру' },
                                                                     class: 'form-control',
                                                                     onchange: "showNextOptions('department', this);")
  .form-group.text-right
    = f.submit 'Отправить', class: 'btn btn-primary btn-lg'

app/views/university_groups/_lecturers.html.haml
%table.table.table-bordered
  = hidden_field_tag "university_group[lecturer_ids][]", nil # default empty array in case nothing will be checked
  - lecturers.in_groups_of(5, false) do |lecturers_row|
    %tr
      - lecturers_row.each do |lecturer|
        %td
          = check_box_tag("university_group[lecturer_ids][]", lecturer.id,
                 university_group.lecturer_ids.include?(lecturer.id))
          = lecturer.fullname

app/views/university_groups/edit.html.haml
.row
  .col
    = link_to '<< Учебные группы', university_groups_path
.row
  .col
    %h4 Редактировать данные учебной группы
.row
  .col-md-3
  .col-md-6
    = render('form', university_group: @university_group)
  .col-md-3
%hr
.row
  .col
    %h4 Связанные преподаватели
.row
  .col-md-12
    = form_for(@university_group)  do |f|
      .form-group#lecturers
        = render('lecturers', lecturers: @lecturers, university_group: @university_group)
      .form-group.text-right
        = f.submit 'Отправить', class: 'btn btn-primary btn-lg'

app/views/university_groups/index.html.haml
.row
  .col
    %h4 Учебные группы
.row
  .col
    %table.table.table-hover.table-bordered
      %thead
        %tr
          %th{scope: 'col'}
            = 'ID'
          %th{scope: 'col'}
            = 'Название'
          %th{scope: 'col'}
            = 'Факультет'
          %th{scope: 'col'}
            = 'Кафедра'
      %tbody
        - @university_groups.each do |university_group|
          %tr
            %th{scope: 'row'}
              = university_group.id
            %td
              = link_to university_group.title, university_group
            %td
              = link_to university_group.faculty.abbreviation, university_group.faculty
            %td
              = link_to university_group.department.abbreviation, university_group.department
            - if current_user.analyst? || current_user.admin?
              %td
                = link_to 'Редактировать', edit_university_group_path(university_group)
            - if current_user.admin?
              %td
                = link_to 'Удалить', university_group_path(university_group), method: :delete, data: { confirm: 'Удалить?' }
        - if current_user.admin?
          %tr
            %td{colspan: '5'}
              = link_to 'Создать', new_university_group_path

app/views/university_groups/new.html.haml
.row
  .col
    = link_to '<< Учебные группы', university_groups_path
.row
  .col
    %h4 Создать учебную группу
.row
  .col-md-3
  .col-md-6
    = render('form', university_group: @university_group)
  .col-md-3

app/views/university_groups/show.html.haml
.row
  .col
    = link_to '<< Учебные группы', university_groups_path
.row
  .col
    %table.table.table-hover.table-bordered
      %thead
        %tr
          %th{scope: 'col'}
            = 'ID'
          %th{scope: 'col'}
            = 'Название'
          %th{scope: 'col'}
            = 'Факультет'
          %th{scope: 'col'}
            = 'Кафедра'
      %tbody
        %tr
          %th{scope: 'row'}
            = @university_group.id
          %td
            = @university_group.title
          %td
            = link_to @university_group.faculty.abbreviation, @university_group.faculty
          %td
            = link_to @university_group.department.abbreviation, @university_group.department
          - if current_user.analyst? || current_user.admin?
            %td
              = link_to 'Редактировать', edit_university_group_path(@university_group)
          - if current_user.admin?
            %td
              = link_to 'Удалить', university_group_path(@university_group), method: :delete, data: { confirm: 'Удалить?' }