config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root  action: :welcome, controller: 'site'
  post 'show_next_options/:entity/(:entity_id)', action: 'show_next_options', controller: 'site'
  post 'start_testing', action: 'start_testing', controller: 'site'
  post 'show_start_button', action: 'show_start_button', controller: 'site'
  post 'show_lecturers_list', action: 'show_lecturers_list', controller: 'site'
  post 'show_stats', action: 'show_stats', controller: 'site'
  get 'main_panel', action: 'main_panel', controller: 'site'

  resources :faculties
  resources :questionnaires
  resources :disciplines
  resources :departments
  resources :university_groups
  resources :lecturers

  scope module: 'api' do
    namespace 'v1' do
      resources :lecturers, only: [:show, :index]
      resources :disciplines, only: [:show, :index]
      resources :faculties, only: [:show, :index]
      resources :departments, only: [:show, :index]
      resources :university_groups, only: [:show, :index]
      resources :questionnaires, only: [:create]
    end
  end
  mount ActionCable.server => '/cable'
end

app/models/discipline.rb
class Discipline < ApplicationRecord
  has_and_belongs_to_many :lecturers
  validates :title,
            uniqueness: { message: 'Дисциплина с таким названием уже существует в базе данных' },
            format: { with: /\A[А-я0-9\-—\s]+\z/, message: 'Используйте кириллические символы/цифры/пробел/тире/дефис' }
  before_create :normalize

  private
    def normalize
      self.title.strip!
      self.title.capitalize!
      self.title.gsub!(/\s{2,}/, ' ')
    end
end

app/controllers/api/v1/disciplines_controller.rb
class Api::V1::DisciplinesController < Api::V1::ApiController
  before_action :set_discipline, only: [:show]
  def index
    render json: ::V1::DisciplineSerializer.new(Discipline.all).serialized_json
  end

  def show
    render json: ::V1::DisciplineSerializer.new(@discipline).serialized_json
  end

  private
  def set_discipline
    @discipline = Discipline.find_by(id: params[:id])
  end
end

app/controllers/disciplines_controller.rb
class DisciplinesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_discipline, only: [:show, :edit, :update, :destroy]
  def index
    @disciplines = Discipline.all
  end

  def new
    @discipline = Discipline.new
  end

  def edit
    @lecturers = Lecturer.all.order('fullname ASC')
  end

  def create
    @discipline = Discipline.new(discipline_params)
    if @discipline.save
      flash[:success] = 'Дисциплина создана'
      redirect_to @discipline
    else
      flash[:danger] = @discipline.errors.full_messages.to_sentence
      render action: :new
    end
  end

  def show
  end

  def update
    if @discipline.update(discipline_params)
      flash[:success] = 'Данные дисциплины обновлены'
      redirect_to @discipline
    else
      flash[:danger] = @discipline.errors.full_messages.to_sentence
      redirect_to edit_discipline_path(@discipline)
    end
  end

  def destroy
    if @discipline.destroy
      flash[:success] = 'Дисциплина удалена'
    else
      flash[:danger] = @discipline.errors.full_messages.to_sentence
    end
    redirect_to disciplines_path
  end

  private
    def set_discipline
      @discipline= Discipline.find_by(id: params[:id])
    end

    def discipline_params
      params.require(:discipline).permit(:title, :lecturer_id, lecturer_ids: [])
    end
end

app/helpers/disciplines_helper.rb
module DisciplinesHelper
end

app/views/disciplines/_form.html.haml
= form_for(discipline) do |f|
  .form-group
    = f.text_field(:title, class: 'form-control', placeholder: 'Название')
  .form-group.text-right
    = f.submit 'Отправить', class: 'btn btn-primary btn-lg'

app/views/disciplines/_lecturers.html.haml
%table.table.table-bordered
  = hidden_field_tag "discipline[lecturer_ids][]", nil # default empty array in case nothing will be checked
  - lecturers.in_groups_of(5, false) do |lecturers_row|
    %tr
      - lecturers_row.each do |lecturer|
        %td
          = check_box_tag("discipline[lecturer_ids][]", lecturer.id,
                 discipline.lecturer_ids.include?(lecturer.id))
          = lecturer.fullname

app/views/disciplines/edit.html.haml
.row
  .col
    = link_to '<< Дисциплины', disciplines_path
.row
  .col
    %h4 Редактировать данные дисциплины
.row
  .col-md-3
  .col-md-6
    = render('form', discipline: @discipline)
  .col-md-3
%hr
.row
  .col
    %h4 Связанные преподаватели
.row
  .col-md-12
    = form_for(@discipline)  do |f|
      .form-group#disciplines
        = render('lecturers', lecturers: @lecturers, discipline: @discipline)
      .form-group.text-right
        = f.submit 'Отправить', class: 'btn btn-primary btn-lg'

app/views/disciplines/index.html.haml
.row
  .col
    %h4 Дисциплины
.row
  .col
    %table.table.table-hover.table-bordered
      %thead
        %tr
          %th{scope: 'col'}
            = 'ID'
          %th{scope: 'col'}
            = 'Название'
      %tbody
        - @disciplines.each do |discipline|
          %tr
            %th{scope: 'row'}
              = discipline.id
            %td
              = link_to discipline.title, discipline
            - if current_user.analyst? || current_user.admin?
              %td
                = link_to 'Редактировать', edit_discipline_path(discipline)
            - if current_user.admin?
              %td
                = link_to 'Удалить', discipline_path(discipline), method: :delete, data: { confirm: 'Удалить?' }
        - if current_user.analyst? || current_user.admin?
          %tr
            %td{colspan: '5'}
              = link_to 'Создать', new_discipline_path

app/views/disciplines/new.html.haml
.row
  .col
    = link_to '<< Дисциплины', disciplines_path
.row
  .col
    %h4 Создать дисциплину
.row
  .col-md-3
  .col-md-6
    = render('form', discipline: @discipline)
  .col-md-3

app/views/disciplines/show.html.haml
.row
  .col
    = link_to '<< Дисциплины', disciplines_path
.row
  .col
    %table.table.table-hover.table-bordered
      %thead
        %tr
          %th{scope: 'col'}
            = 'ID'
          %th{scope: 'col'}
            = 'Название'
      %tbody
        %tr
          %th{scope: 'row'}
            = @discipline.id
          %td
            = @discipline.title
          - if current_user.analyst? || current_user.admin?
            %td
              = link_to 'Редактировать', edit_discipline_path(@discipline)
          - if current_user.admin?
            %td
              = link_to 'Удалить', discipline_path(@discipline), method: :delete, data: { confirm: 'Удалить?' }