config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root  action: :welcome, controller: 'site'
  post 'show_next_options/:entity/(:entity_id)', action: 'show_next_options', controller: 'site'
  post 'start_testing', action: 'start_testing', controller: 'site'
  post 'show_start_button', action: 'show_start_button', controller: 'site'
  post 'show_lecturers_list', action: 'show_lecturers_list', controller: 'site'
  post 'show_stats', action: 'show_stats', controller: 'site'
  get 'main_panel', action: 'main_panel', controller: 'site'

  resources :faculties
  resources :questionnaires
  resources :disciplines
  resources :departments
  resources :university_groups
  resources :lecturers

  scope module: 'api' do
    namespace 'v1' do
      resources :lecturers, only: [:show, :index]
      resources :disciplines, only: [:show, :index]
      resources :faculties, only: [:show, :index]
      resources :departments, only: [:show, :index]
      resources :university_groups, only: [:show, :index]
      resources :questionnaires, only: [:create]
    end
  end
  mount ActionCable.server => '/cable'
end

app/models/faculty.rb
class Faculty < ApplicationRecord
  has_many :departments, dependent: :destroy
  has_many :university_groups, dependent: :destroy
  validates :title,
            format: { with: /\A[А-я\-—\s]+\z/, message: 'Используйте кириллические символы/пробел/тире/дефис' },
            uniqueness: {message: 'Факультет с таким названием уже существует в базе данных' },
            length: { maximum: 200, too_long: "Длина введенного названия больше максимальной — %{count}" }
  validates :abbreviation,
            format: { with: /\A[А-я]+\z/, message: 'Используйте только кириллические символы' },
            uniqueness: {message: 'Факультет с такой аббревиатурой уже существует в базе данных' },
            length: { maximum: 15, too_long: "Длина введенной аббревиатуры больше максимальной — %{count}" }
  before_create :normalize

  private
    def normalize
      self.title.strip!
      self.title.capitalize!
      self.title.gsub!(/\s{2,}/, ' ')
    end
end

app/controllers/api/v1/faculties_controller.rb
class Api::V1::FacultiesController < Api::V1::ApiController
  before_action :set_faculty, only: [:show]
  def index
    render json: ::V1::FacultySerializer.new(Faculty.all).serialized_json
  end

  def show
    render json: ::V1::FacultySerializer.new(@faculty).serialized_json
  end

  private
  def set_faculty
    @faculty = Faculty.find_by(id: params[:id])
  end
end

app/controllers/faculties_controller.rb
class FacultiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_faculty, only: [:show, :edit, :update, :destroy]

  def index
    @faculties = Faculty.all
  end

  def new
    @faculty = Faculty.new
  end

  def edit
  end

  def create
    @faculty = Faculty.new(faculty_params)
    if @faculty.save
      flash[:success] = 'Факультет создан'
      redirect_to @faculty
    else
      flash[:danger] = @faculty.errors.full_messages.to_sentence
      render action: :new
    end
  end

  def show
  end

  def update
    if @faculty.update(faculty_params)
      flash[:success] = 'Данные факультета обновлены'
      redirect_to @faculty
    else
      flash[:danger] = @faculty.errors.full_messages.to_sentence
      redirect_to edit_faculty_path(@faculty)
    end
  end

  def destroy
    if @faculty.destroy
      flash[:success] = 'Факультет удален'
    else
      flash[:danger] = @faculty.errors.full_messages.to_sentence
    end
    redirect_to faculties_path
  end

  private
    def set_faculty
      @faculty = Faculty.find_by(id: params[:id])
    end

    def faculty_params
      params.require(:faculty).permit(:title, :abbreviation)
    end
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/views/faculties/_form.html.haml
= form_for(faculty) do |f|
  .form-group
    = f.text_field(:title, class: 'form-control', placeholder: 'Название')
  .form-group
    = f.text_field(:abbreviation, class: 'form-control', placeholder: 'Аббревиатура')
  .form-group.text-right
    = f.submit 'Отправить', class: 'btn btn-primary btn-lg'

app/views/faculties/edit.html.haml
.row
  .col
    = link_to '<< Факультеты', faculties_path
.row
  .col
    %h4 Редактировать данные факультета
.row
  .col-md-3
  .col-md-6
    = render('form', faculty: @faculty)
  .col-md-3

app/views/faculties/index.html.haml
.row
  .col
    %h4 Факультеты
.row
  .col
    %table.table.table-hover.table-bordered
      %thead
        %tr
          %th{scope: 'col'}
            = 'ID'
          %th{scope: 'col'}
            = 'Название'
          %th{scope: 'col'}
            = 'Аббревиатура'
      %tbody
        - @faculties.each do |faculty|
          %tr
            %th{scope: 'row'}
              = faculty.id
            %td
              = link_to faculty.title, faculty
            %td
              = faculty.abbreviation
            - if current_user.analyst? || current_user.admin?
              %td
                = link_to 'Редактировать', edit_faculty_path(faculty)
            -  if current_user.admin?
              %td
                = link_to 'Удалить', faculty_path(faculty), method: :delete, data: { confirm: 'Удалить?' }
        - if current_user.analyst? || current_user.admin?
          %tr
            %td{colspan: '5'}
              = link_to 'Создать', new_faculty_path

app/views/faculties/new.html.haml
.row
  .col
    = link_to '<< Факультеты', faculties_path
.row
  .col
    %h4 Создать факультет
.row
  .col-md-3
  .col-md-6
    = render('form', faculty: @faculty)
  .col-md-3

app/views/faculties/show.html.haml
.row
  .col
    = link_to '<< Факультеты', faculties_path
.row
  .col
    %table.table.table-hover.table-bordered
      %thead
        %tr
          %th{scope: 'col'}
            = 'ID'
          %th{scope: 'col'}
            = 'Название'
          %th{scope: 'col'}
            = 'Кафедры'
      %tbody
        %tr
          %th{scope: 'row'}
            = @faculty.id
          %td
            = @faculty.title
          %td
            - @faculty.departments.each do |department|
              %p
                = link_to department.title, department
          - if current_user.analyst? || current_user.admin?
            %td
              = link_to 'Редактировать', edit_faculty_path(@faculty)
          - if current_user.admin?
            %td
              = link_to 'Удалить', faculty_path(@faculty), method: :delete, data: { confirm: 'Удалить?' }