config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root  action: :welcome, controller: 'site'
  post 'show_next_options/:entity/(:entity_id)', action: 'show_next_options', controller: 'site'
  post 'start_testing', action: 'start_testing', controller: 'site'
  post 'show_start_button', action: 'show_start_button', controller: 'site'
  post 'show_lecturers_list', action: 'show_lecturers_list', controller: 'site'
  post 'show_stats', action: 'show_stats', controller: 'site'
  get 'main_panel', action: 'main_panel', controller: 'site'

  resources :faculties
  resources :questionnaires
  resources :disciplines
  resources :departments
  resources :university_groups
  resources :lecturers

  scope module: 'api' do
    namespace 'v1' do
      resources :lecturers, only: [:show, :index]
      resources :disciplines, only: [:show, :index]
      resources :faculties, only: [:show, :index]
      resources :departments, only: [:show, :index]
      resources :university_groups, only: [:show, :index]
      resources :questionnaires, only: [:create]
    end
  end
  mount ActionCable.server => '/cable'
end

app/models/department.rb
class Department < ApplicationRecord
  belongs_to :faculty
  has_many :university_groups, dependent: :destroy
  has_and_belongs_to_many :lecturers
  validates :title,
            format: { with: /\A[А-я\-—\s]+\z/, message: 'Используйте кириллические символы/пробел/тире/дефис' },
            uniqueness:  {message: 'Кафедра с таким названием уже существует в базе данных' },
            length: { maximum: 200, too_long: "Длина введенного названия больше максимальной — %{count}" }
  validates :abbreviation,
            format: { with: /\A[А-я]+\z/, message: 'Используйте только кириллические символы' },
            uniqueness: {message: 'Кафедра с такой аббревиатурой уже существует в базе данных' },
            length: { maximum: 15, too_long: "Длина введенной аббревиатуры больше максимальной — %{count}"}
  validates :faculty_id, presence: { message: 'Не указан факультет' }
  before_create :normalize

  private
    def normalize
      self.title.strip!
      self.title.capitalize!
      self.title.gsub!(/\s{2,}/, ' ')
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def welcome
    @total_count = Questionnaire.count
  end

  def show_next_options
    model = params[:model]
    model_id = params[:model_id]
    @parent_form_group_id = params[:parent_form_group_id]

    case model
    when 'faculty'
      options = Faculty.find_by(id: model_id).departments
    when 'department'
      options = Department.find_by(id: model_id).university_groups
    end

    @options_partial = ApplicationController.render(partial: 'site/options', locals: {
        options: options
    })

    respond_to do |format|
      format.js
    end
  end

  def show_start_button
    university_group = UniversityGroup.find_by(id: params[:university_group_id])
    lecturers_count = university_group.lecturers.count
    disabled = true if lecturers_count == 0
    @start_button_partial = ApplicationController.render(partial: 'site/start_button', locals: {
        university_group: university_group,
        lecturers_count: lecturers_count,
        disabled: disabled
    })

    respond_to do |format|
      format.js
    end
  end

  def start_testing
    @university_group = UniversityGroup.find(params[:university_group_id])
    session[:lecturers_ids] = @university_group.lecturers.ids
    session[:university_group_id] = @university_group.id

    respond_to do |format|
      format.js
    end
  end

  def show_stats
    calculation_type = params[:calculation_type]
    lecturer_id = params[:lecturer_id]
    lecturer = Lecturer.find_by(id: lecturer_id)
    # if no particular discipline selected then include all lecturer's disciplines
    disciplines = params[:discipline_id] == '' ? lecturer.disciplines.ids : [params[:discipline_id]]
    number_of_questionnaires = lecturer.questionnaires.count

    summary_stats = lecturer.get_summary_stats(calculation_type, disciplines)
    average = lecturer.get_average(summary_stats)
    occurrences_stats = lecturer.get_occurrences_stats
    summary_stats_for_charts = lecturer.transform_hash_keys(summary_stats)
    occurrences_stats_for_charts = lecturer.transform_hash_keys(occurrences_stats)

    @stats_table_partial = ApplicationController.render(partial: 'lecturers/stats_table', locals: {
                                                                                    summary_stats: summary_stats,
                                                                                    average: average,
                                                                                    number_of_questionnaires: number_of_questionnaires
    })

    @summary_pie_chart_partial = ApplicationController.render(partial: 'lecturers/pie_chart', locals: {
                                                                                                values_hash: summary_stats_for_charts.except('№7'),
                                                                                                title: 'Общее',
                                                                                                id: 'summary'
    })

    @occurrences_pie_charts = []
    occurrences_stats_for_charts.except('№7').each do |question, occurrences|
      @occurrences_pie_charts << ApplicationController.render(partial: 'lecturers/pie_chart', locals: {
                                                                                                values_hash: occurrences,
                                                                                                title: "Распределение баллов по #{question}",
                                                                                                id: question
                                                                                            })
    end


    respond_to do |format|
      format.js
    end
  end
end

app/views/site/_departments_options.html.haml
.form-group
  = collection_select(:department, :id, faculty.departments, :id, :title,
                                        { prompt: 'Выберите кафедру'},
                                        { class: 'form-control form-control-lg',
                                          onchange: 'getNextHtmlSelect(this);'})

app/views/site/_faculties_options.html.haml
.form-group
  = collection_select(:faculty, :id, Faculty.all, :id, :title,
                                        { prompt: 'Выберите факультет'},
                                        { class: 'form-control form-control-lg',
                                          onchange: 'getNextHtmlSelect(this);'})

app/views/site/_lecturers.html.haml
- lecturers.in_groups_of(3) do |lecturer|
  .form-check
    = f.check_box(:lecturer_ids, {}, lecturer.id)
    = lecturer.fullname

app/views/site/_options.html.haml
%option
  = '---'
- options.each do |option|
  %option{ value: option.id }
    = option.title

app/views/site/_start_button.html.haml
%h5
  Количество преподавателей для учебной группы <b>#{university_group.title}</b>: #{lecturers_count}.
.form-group
  = form_with(url: start_testing_path, method: 'post', remote: true) do |f|
    = f.hidden_field(:university_group_id, value: university_group.id)
    - if disabled
      = f.submit 'Начать анкетирование', class: 'btn btn-primary btn-lg', disabled: true
    - else
      = f.submit 'Начать анкетирование', class: 'btn btn-primary btn-lg'

app/views/site/_university_groups_options.html.haml
.form-group
  = collection_select(:university_group, :id, department.university_groups, :id, :title,
                                        { prompt: 'Выберите учебную группу'},
                                        { class: 'form-control form-control-lg',
                                          onchange: 'getNextHtmlSelect(this);'})

app/views/site/main_panel.html.haml
.row
  .col-md-3
  .col-md-2
    = link_to 'Преподаватели', lecturers_path, class: 'main-panel-link'
  .col-md-2
    = link_to 'Факультеты', faculties_path, class: 'main-panel-link'
  .col-md-2
    = link_to 'Кафедры', departments_path, class: 'main-panel-link'
  .col-md-3
%hr
.row
  .col-md-3
  .col-md-2
    = link_to 'Дисциплины', disciplines_path, class: 'main-panel-link'
  .col-md-2
    = link_to 'Группы', university_groups_path, class: 'main-panel-link'
  .col-md-2
  .col-md-3
%hr
.row
  .col-md-3
    %sup.token.text-muted
      = "token: #{current_user.auth_token}"
  .col-md-5
  .col-md-3
    = current_user.email
    %sup.role
      = current_user.role
  .col-md-1
    = link_to 'Выйти', destroy_user_session_path, method: :delete, class: 'main-panel-link-logout'

app/views/site/show_lecturers_list.js.haml
:plain
  $('#lecturers').html("#{j(@lecturers_list_partial)}");

app/views/site/show_next_options.js.haml
:plain
  $("##{@parent_form_group_id} + .form-group select").html("#{j(@options_partial)}"); // update next html select tag options

app/views/site/show_start_button.js.haml
:plain
  $('#startButton').html("#{j(@start_button_partial)}");

app/views/site/show_stats.js.haml
:plain
  $('#statsTable').html("#{j(@stats_table_partial)}");
  $('#mainPieChart').html("#{j(@summary_pie_chart_partial)}");
  $('#firstQuestionPieChart').html("#{j(@occurrences_pie_charts[0])}");
  $('#secondQuestionPieChart').html("#{j(@occurrences_pie_charts[1])}");
  $('#thirdQuestionPieChart').html("#{j(@occurrences_pie_charts[2])}");
  $('#fourthQuestionPieChart').html("#{j(@occurrences_pie_charts[3])}");
  $('#fifthQuestionPieChart').html("#{j(@occurrences_pie_charts[4])}");
  $('#sixthQuestionPieChart').html("#{j(@occurrences_pie_charts[5])}");

app/views/site/start_testing.js.haml
:plain
  $("#facultiesOptions").hide();
  $("#departmentsOptions").hide();
  $("#universityGroupsOptions").hide();
  $("#startButton").hide();
  $("#totalCountContainer").hide();

  $.ajax({
        url: '/questionnaires/new',
        type: 'GET',
        dataType: 'script'
    });

app/views/site/welcome.html.haml
.row
  .col-md-3
    = render('shared/total_count')
  .col-md-6
    .form-group#facultiesOptions
      = collection_select(:faculty, :id, Faculty.all, :id, :title, { prompt: 'Выберите факультет' },
                                                                       class: 'form-control form-control-lg',
                                                                       onchange: "showNextOptions('faculty', this);")
    .form-group#departmentsOptions
      = collection_select(:department, :id, Department.all, :id, :title, { prompt: 'Выберите кафедру' },
                                                                       class: 'form-control form-control-lg',
                                                                       onchange: "showNextOptions('department', this);")
    .form-group#universityGroupsOptions
      = collection_select(:university_group, :id, UniversityGroup.all, :id, :title, { prompt: 'Выберите учебную группу' },
                                                                       class: 'form-control form-control-lg',
                                                                       onchange: "showStartButton(this);")
    .form-group.text-center#startButton
  .col-md-3
.row
  .col#questionnaireForm